# Generated by Django 5.1.1 on 2024-10-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_amherst_algo', '0002_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
